### ISSUE TITLE
Scrolldown button color same as chat background

### ISSUE THREAD

**Issue by devils-shadow** [MasterGroosha/telegram-soliddark-theme#2]
this button should be changed to a lighter shade of grey (maybe make it same as the text input box?) http://i.imgur.com/RpCPdkr.png so it doesn't blend with the chat background color.

As a side edit: could you maybe make a theme variant that uses the default windows 10 blue color instead of green? (#266388 or #002f4d to match the default taskbar color)

**Comment by MasterGroosha** [comment]
Well, unfortunately, there's no separate key for "scroll to bottom" button. It is shared with `windowBg` which is one of main keys and "breaks" the whole design if changed. Maybe we should open an issue to create separate keys for "scroll to bottom".

As for the "side edit": not is the nearest future, sorry. First I need to "fix" all the keys so main accent colors can be easily replaced for the whole app, not just 2 or 3 windows. I'll look into your question then.

**Comment by devils-shadow** [comment]
Aight, no problem regarding the side edit. Maybe you can report the main issue in the telegram desktop github? You obviously know more about the issue than me and I'm sure you'd be able to explain to them what the issue is in more detail.

**Comment by MasterGroosha** [comment]
Well, that's definetely TDesktop's issue: https://github.com/telegramdesktop/tdesktop/issues/2852
I'm leaving this issue open until colors are separated.

**Comment by devils-shadow** [comment]
Much appreciated, thank you!

**Comment by MasterGroosha** [comment]
Done with 8f0824c82129e4998dd335cc7d08e522ce8639d0

![image](https://cloud.githubusercontent.com/assets/2780044/22019212/9a14cdf0-dcc3-11e6-8560-60d21a1f4c85.png)
