### ISSUE TITLE
Suggestion to Android version

### ISSUE THREAD

**Issue by ivomarsan** [MasterGroosha/telegram-soliddark-theme#3]
I propose to change `actionBarDefault` and `avatar_backgroundActionBarBlue` to `rgba(60, 60, 60, 255)`
I think it gets coolest. Its my suggestion 👍 

I use your theme on Android and Desktop version.

**Comment by MasterGroosha** [comment]
Hello @ivomarsan!
Thank you for your suggestion! I'll check the proposed color and see how the theme will look like.
